spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}

keycloak:
  realm: 'eng-self'
  auth-server-url: http://localhost:18080
  ssl-required: external
  resource: 'eng-self'
  credentials:
    secret: 'p4XX4oUQbUA4Y3IfeTC9ihW2HjFkbaEr'
  use-resource-role-mappings: true
  bearer-only: true

other:
  service:
    url:
      profile: http://localhost:8084/users

server:
  port: 8888