spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  kafka:
    bootstrap-servers: localhost:9092
  cache:
    ttl: 1 # Время жизни кэша в часах

keycloak:
  realm: 'eng-self'
  auth-server-url: http://localhost:18080
  ssl-required: external
  resource: 'eng-self'
  credentials:
    secret: 'p4XX4oUQbUA4Y3IfeTC9ihW2HjFkbaEr'
  use-resource-role-mappings: true
  bearer-only: true

other:
  service:
    url:
      dictionary: http://localhost:8081/word-progress
      reading: http://localhost:8082/book-progress
      testing: http://localhost:8083/user-test-results
      tracker: http://localhost:8085/trackers

server:
  port: 8086