version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: 'zookeeper'
    env_file:
      - kafka.env
    ports:
      - "22181:2181"
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "9092:9092"
    env_file:
      - kafka.env
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: 'redis'
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - redis:/data

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data:
    driver: local
  redis:
    driver: local